import asyncio
import re
from playwright.async_api import Playwright, async_playwright, expect


async def run(playwright: Playwright) -> None:
    browser = await playwright.chromium.launch(headless=False)
    context = await browser.new_context()
    page = await context.new_page()
    await page.goto("http://192.168.1.128/login")
    await page.get_by_placeholder("用户名").click()
    await page.get_by_placeholder("用户名").fill("")
    await page.locator("#rememberme").click()
    await page.get_by_text("登录").click()
    await page.locator("#rememberme").fill("")
    await page.goto("http://192.168.1.128/index")
    await page.get_by_text("系统管理").click()
    await page.get_by_text("用户管理").click()
    await page.locator("[type="text"]").click()
    await page.locator("[type="text"]").fill("")
    await page.locator("[type="text"]").fill("")
    await page.get_by_text("搜索").click()
    await page.get_by_text("所有 正常 停用").click()
    await page.locator("unknown").click()
    await page.get_by_text("所有 正常 停用").click()
    await page.get_by_text("所有 正常 停用").click()
    await page.get_by_text("所有 正常 停用").click()
    await page.get_by_text("所有 正常 停用").click()
    await page.get_by_text("所有 正常 停用").click()
    await page.get_by_text("所有 正常 停用").click()
    await page.get_by_text("所有 正常 停用").click()
    await page.get_by_text("所有 正常 停用").click()
    await page.locator("unknown").click()
    await page.get_by_text("所有 正常 停用").fill("")
    await page.locator("unknown").click()
    await page.get_by_text("所有 正常 停用").fill("")
    await page.get_by_text("市场部门").click()
    await page.get_by_text("研发部门").click()
    await page.get_by_text("岗位管理").click()
    await page.get_by_text("字典管理").click()
    await page.get_by_placeholder("开始时间").click()
    await page.get_by_text("12").click()
    await page.get_by_placeholder("结束时间").click()
    await page.get_by_placeholder("开始时间").click()
    await page.get_by_placeholder("开始时间").click()
    await page.locator("[type="text"]").click()
    await page.get_by_text("系统监控").click()
    await page.get_by_text("定时任务").click()
    await page.get_by_text("服务监控").click()
    await page.get_by_text("DESKTOP-8IRKJC0").click()
    await page.get_by_text("用户使用率").click()
    await page.get_by_text("2.87%").click()
    await page.get_by_text("系统工具").click()
    await page.get_by_text("代码生成").click()
    await page.get_by_text("创建").click()
    await page.get_by_placeholder("请输入文本").click()
    await page.get_by_placeholder("请输入文本").fill("")
    await page.get_by_text("创建表语句(支持多个建表语句)：").click()
    await page.get_by_text("关闭").click()
    await page.get_by_text("系统监控").click()
    await page.get_by_text("在线用户").click()
    await page.get_by_text("服务监控").click()
    await page.get_by_text("缓存监控").click()
    await page.get_by_text("系统管理").click()
    await page.get_by_text("参数设置").click()
    await page.get_by_text("新增").click()
    await page.locator("#configName").click()

    # ---------------------
    await context.close()
    await browser.close()


async def main() -> None:
    async with async_playwright() as playwright:
        await run(playwright)


asyncio.run(main())